### ISSUE TITLE
Exclude the FFI from the example in the release in favour of a gemspec definition

### ISSUE THREAD

**Issue by mensfeld** [build-security/opa-rails-middleware#5]
My name is Maciej Mensfeld and I run a research security project called WhiteSource https://diffend.io.

I wanted to suggest an improvement.

I noticed, that the example here: https://github.com/build-security/opa-rails-middleware/tree/main/example has an extensions directory that links to FFI. Is there any reason not to use the FFI that is provided via RubyGem and keep the FFI as a Gemfile definition instead of including it?

**Comment by yashtewari** [comment]
Hi Maciej! Thank you so much for your suggestion.

It turns out that our example directory, and by extension this FFI issue, is obsolete. I will however keep it in mind when we add a new example.

**Comment by mensfeld** [comment]
Thank you!
