### ISSUE TITLE
Exclude test directory from the gem release

### ISSUE THREAD

**Issue by mensfeld** [build-security/opa-rails-middleware#6]
Hey, it's me again.

Since content of the gems is in majority of cases used only for business / production purposes, I wanted to suggest exclusion of the test directory from the rubygems releases. This would make the gem smaller as well as would make work of security people like me much easier.

Have a great day.

**Comment by yashtewari** [comment]
Hey there! Thanks for the suggestion. The top level `tests` directory was already excluded. I've also excluded the `example ` directory altogether, which contained its own tests.
